# Generated by Django 5.2.6 on 2025-10-07 05:35

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asm', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='states', chained_model_field='state', related_name='zone_managers', to='master.district')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_managers', to='auth.group')),
                ('offices', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='districts', chained_model_field='district', related_name='zone_managers', to='master.office')),
                ('states', models.ManyToManyField(blank=True, related_name='zone_managers', to='master.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZMDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('application_target', models.FloatField(blank=True, default=0, null=True)),
                ('pop_target', models.FloatField(blank=True, default=0, null=True)),
                ('esign_target', models.FloatField(blank=True, default=0, null=True)),
                ('new_taluk_target', models.FloatField(blank=True, default=0, null=True)),
                ('new_live_partners_target', models.FloatField(blank=True, default=0, null=True)),
                ('activations_target', models.FloatField(blank=True, default=0, null=True)),
                ('calls_target', models.FloatField(blank=True, default=0, null=True)),
                ('sd_collection_target', models.FloatField(blank=True, default=0, null=True)),
                ('application_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('pop_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('esign_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('new_taluk_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('new_live_partners_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('activations_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('calls_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('sd_collection_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zm_targets', to='asm.asm')),
                ('zone_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_targets', to='zonemanager.zonemanager')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('zone_manager', 'asm', 'date')},
            },
        ),
    ]
