# Generated by Django 4.2.19 on 2025-09-16 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0006_alter_pincodedata_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', models.ManyToManyField(blank=True, related_name='zone_districts', to='master.pincodedata')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('offices', models.ManyToManyField(blank=True, related_name='zone_offices', to='master.pincodedata')),
                ('states', models.ManyToManyField(blank=True, related_name='zone_states', to='master.pincodedata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
