# Generated by Django 4.2.19 on 2025-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_pincodedata_latitude_and_more'),
        ('zonemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemanager',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='offices',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='states',
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='pincodes',
            field=models.ManyToManyField(blank=True, related_name='zone_managers', to='master.pincodedata'),
        ),
    ]
