# Generated by Django 4.2.19 on 2025-09-16 11:52

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_pincodedata_latitude_and_more'),
        ('zonemanager', '0002_remove_zonemanager_districts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemanager',
            name='pincodes',
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='statename', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_district', to='master.pincodedata'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='office',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_office', to='master.pincodedata'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'statename__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_state', to='master.pincodedata'),
        ),
    ]
