# Generated by Django 4.2.19 on 2025-09-16 11:55

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_pincodedata_latitude_and_more'),
        ('zonemanager', '0003_remove_zonemanager_pincodes_zonemanager_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonemanager',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='state', chained_model_field='statename', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_district', to='master.pincodedata'),
        ),
    ]
