# Generated by Django 4.2.19 on 2025-09-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_pincodedata_latitude_and_more'),
        ('zonemanager', '0004_alter_zonemanager_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonemanager',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_state', to='master.pincodedata'),
        ),
    ]
