# Generated by Django 4.2.19 on 2025-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_pincodedata_latitude_and_more'),
        ('zonemanager', '0005_alter_zonemanager_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemanager',
            name='district',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='office',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='state',
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='zone_districts', to='master.pincodedata'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='zone_offices', to='master.pincodedata'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='zone_states', to='master.pincodedata'),
        ),
    ]
