# Generated by Django 4.2.19 on 2025-09-16 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zonemanager', '0006_remove_zonemanager_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='offices',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='states',
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='statename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='officetypes',
            field=models.ManyToManyField(blank=True, to='zonemanager.officetype'),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='districts',
            field=models.ManyToManyField(blank=True, to='zonemanager.district'),
        ),
    ]
