# Generated by Django 4.2.19 on 2025-09-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonemanager', '0008_state_alter_district_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemanager',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='group',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='officetypes',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='statename',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='user',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='OfficeType',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='ZoneManager',
        ),
    ]
