# Generated by Django 4.2.19 on 2025-09-16 12:57

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_state_district_office'),
        ('zonemanager', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonemanager',
            name='districts',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='states', chained_model_field='state', related_name='zone_managers', to='master.district'),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='offices',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='districts', chained_model_field='district', related_name='zone_managers', to='master.office'),
        ),
    ]
