# Generated by Django 4.2.19 on 2025-09-17 04:49

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_state_district_office'),
        ('zonemanager', '0011_alter_zonemanager_districts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemanager',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='offices',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='states',
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_managers', to='master.district'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='office',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_managers', to='master.office'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_managers', to='master.state'),
        ),
    ]
