# Generated by Django 4.2.19 on 2025-09-17 04:54

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0010_pincodedata_district_ref_pincodedata_office_ref_and_more'),
        ('zonemanager', '0012_remove_zonemanager_districts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonemanager',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_managers', to='master.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_managers', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='office',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_managers', to='master.office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_managers', to='master.state', verbose_name='State'),
        ),
    ]
