# Generated by Django 4.2.19 on 2025-09-17 04:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_remove_pincodedata_district_ref_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('zonemanager', '0013_alter_zonemanager_district_alter_zonemanager_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemanager',
            name='district',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='office',
        ),
        migrations.RemoveField(
            model_name='zonemanager',
            name='state',
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='districts',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='states', chained_model_field='state', related_name='zone_managers', to='master.district'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='offices',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='districts', chained_model_field='district', related_name='zone_managers', to='master.office'),
        ),
        migrations.AddField(
            model_name='zonemanager',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='zone_managers', to='master.state'),
        ),
        migrations.AlterField(
            model_name='zonemanager',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
