# Generated by Django 4.2.19 on 2025-09-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('zonemanager', '0014_remove_zonemanager_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonemanager',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_managers', to='auth.group'),
        ),
    ]
