# Generated by Django 4.2.19 on 2025-09-17 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0002_alter_asm_zone_manager'),
        ('zonemanager', '0015_alter_zonemanager_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZMDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Application', 'Application'), ('POP', 'POP'), ('E-Sign', 'E-Sign'), ('New Taluk', 'New Taluk'), ('New Live Partners', 'New Live Partners'), ('Activations', 'Activations'), ('Calls', 'Calls'), ('SD Collection', 'SD Collection (Rs)')], max_length=50, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('target_value', models.FloatField(blank=True, default=0, null=True)),
                ('achievement_value', models.FloatField(blank=True, default=0, null=True)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zm_targets', to='asm.asm')),
                ('zone_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_targets', to='zonemanager.zonemanager')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('zone_manager', 'asm', 'category', 'date')},
            },
        ),
    ]
