# Generated by Django 4.2.19 on 2025-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0002_alter_asm_zone_manager'),
        ('zonemanager', '0016_zmdailytarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zmdailytarget',
            old_name='achievement_value',
            new_name='activations_achieve',
        ),
        migrations.RenameField(
            model_name='zmdailytarget',
            old_name='target_value',
            new_name='activations_target',
        ),
        migrations.AlterUniqueTogether(
            name='zmdailytarget',
            unique_together={('zone_manager', 'asm', 'date')},
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='application_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='application_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='calls_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='calls_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='esign_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='esign_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='new_live_partners_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='new_live_partners_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='new_taluk_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='new_taluk_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='pop_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='pop_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='sd_collection_achieve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zmdailytarget',
            name='sd_collection_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='zmdailytarget',
            name='category',
        ),
    ]
