# Generated by Django 5.2.6 on 2025-09-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circlename', models.CharField(blank=True, default='', max_length=100)),
                ('regionname', models.CharField(blank=True, default='', max_length=100)),
                ('divisionname', models.CharField(blank=True, default='', max_length=100)),
                ('officename', models.CharField(blank=True, default='', max_length=150)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('officetype', models.CharField(blank=True, default='', max_length=50)),
                ('delivery', models.CharField(blank=True, default='', max_length=50)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('statename', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='master.state')),
            ],
            options={
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('officetype', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='master.district')),
            ],
            options={
                'unique_together': {('name', 'district')},
            },
        ),
    ]
