# Generated by Django 4.2.19 on 2025-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Zone', max_length=100, unique=True)),
                ('code', models.CharField(default='ZONE001', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
    ]
