# Generated by Django 4.2.19 on 2025-09-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(default='Z001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(default='Unknown Zone', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown State', max_length=100, unique=True)),
                ('code', models.CharField(default='S001', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('zone', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='master.zone')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown District', max_length=100)),
                ('code', models.CharField(default='D001', max_length=20)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='master.state')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Taluk', max_length=100)),
                ('code', models.CharField(default='T001', max_length=20)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taluks', to='master.district')),
            ],
            options={
                'verbose_name': 'Taluk',
                'verbose_name_plural': 'Taluks',
                'unique_together': {('name', 'district')},
            },
        ),
    ]
