# Generated by Django 4.2.19 on 2025-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_zone_code_alter_zone_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circlename', models.CharField(blank=True, default='', max_length=100)),
                ('regionname', models.CharField(blank=True, default='', max_length=100)),
                ('divisionname', models.CharField(blank=True, default='', max_length=100)),
                ('officename', models.CharField(blank=True, default='', max_length=150)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('officetype', models.CharField(blank=True, default='', max_length=50)),
                ('delivery', models.CharField(blank=True, default='', max_length=50)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('statename', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
            ],
        ),
    ]
