# Generated by Django 4.2.19 on 2025-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_pincodedata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincodedata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pincodedata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
