# Generated by Django 4.2.19 on 2025-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_pincodedata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincodedata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pincodedata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
