# Generated by Django 4.2.19 on 2025-09-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_officetype_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.DeleteModel(
            name='OfficeType',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
