# Generated by Django 4.2.19 on 2025-09-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_state_district_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincodedata',
            name='district_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.district'),
        ),
        migrations.AddField(
            model_name='pincodedata',
            name='office_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.office'),
        ),
        migrations.AddField(
            model_name='pincodedata',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.state'),
        ),
    ]
