# Generated by Django 4.2.19 on 2025-09-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_pincodedata_district_ref_pincodedata_office_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincodedata',
            name='district_ref',
        ),
        migrations.RemoveField(
            model_name='pincodedata',
            name='office_ref',
        ),
        migrations.RemoveField(
            model_name='pincodedata',
            name='state_ref',
        ),
    ]
