# Generated by Django 5.2.6 on 2025-10-07 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asm', '0005_delete_asmtask'),
        ('master', '0002_taskcategory'),
        ('zonemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASMTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(default='No details provided')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('hold', 'Hold')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='asm.asm')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='master.taskcategory')),
                ('zone_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='zonemanager.zonemanager')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
