# Generated by Django 5.2.6 on 2025-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asmtask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
