# Generated by Django 5.2.6 on 2025-09-27 06:46

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASMDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('application_target', models.FloatField(default=0)),
                ('pop_target', models.FloatField(default=0)),
                ('esign_target', models.FloatField(default=0)),
                ('new_taluk_target', models.FloatField(default=0)),
                ('new_live_partners_target', models.FloatField(default=0)),
                ('activations_target', models.FloatField(default=0)),
                ('calls_target', models.FloatField(default=0)),
                ('sd_collection_target', models.FloatField(default=0)),
                ('application_achieve', models.FloatField(default=0)),
                ('pop_achieve', models.FloatField(default=0)),
                ('esign_achieve', models.FloatField(default=0)),
                ('new_taluk_achieve', models.FloatField(default=0)),
                ('new_live_partners_achieve', models.FloatField(default=0)),
                ('activations_achieve', models.FloatField(default=0)),
                ('calls_achieve', models.FloatField(default=0)),
                ('sd_collection_achieve', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=120)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='states', chained_model_field='state', related_name='asms', to='master.district')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asms', to='auth.group')),
                ('offices', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='districts', chained_model_field='district', related_name='asms', to='master.office')),
                ('states', models.ManyToManyField(blank=True, related_name='asms', to='master.state')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
