# Generated by Django 5.2.6 on 2025-09-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0003_alter_district_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', models.ManyToManyField(related_name='districts', to='master.district')),
                ('states', models.ManyToManyField(related_name='states', to='master.state')),
                ('taluks', models.ManyToManyField(related_name='taluks', to='master.taluk')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zones', models.ManyToManyField(related_name='zones', to='master.zone')),
            ],
        ),
    ]
