# Generated by Django 5.2.6 on 2025-09-10 04:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0003_alter_district_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asm',
            options={'verbose_name': 'ASM'},
        ),
        migrations.RemoveField(
            model_name='asm',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='asm',
            name='states',
        ),
        migrations.RemoveField(
            model_name='asm',
            name='taluks',
        ),
        migrations.RemoveField(
            model_name='asm',
            name='zones',
        ),
        migrations.AddField(
            model_name='asm',
            name='code',
            field=models.CharField(default='S001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='asm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asm',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asm',
            name='last_password_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asm',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='asm',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asm',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ASMDistrictMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='S001', max_length=20, unique=True)),
                ('asm_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='asm.asm')),
                ('district_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='master.district')),
            ],
        ),
        migrations.CreateModel(
            name='ASMStateMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='S001', max_length=20, unique=True)),
                ('asm_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='asm.asm')),
                ('state_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='master.state')),
            ],
        ),
        migrations.CreateModel(
            name='ASMTalukMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='S001', max_length=20, unique=True)),
                ('asm_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='asm.asm')),
                ('region_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='master.taluk')),
            ],
        ),
        migrations.CreateModel(
            name='ASMZoneMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='S001', max_length=20, unique=True)),
                ('asm_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='asm.asm')),
                ('zone_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='master.zone')),
            ],
        ),
    ]
