# Generated by Django 4.2.19 on 2025-09-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonemanager', '0015_alter_zonemanager_group'),
        ('asm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asm',
            name='zone_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asms', to='zonemanager.zonemanager'),
        ),
    ]
