# Generated by Django 5.2.6 on 2025-09-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asm', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('zonemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asm',
            name='zone_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asms', to='zonemanager.zonemanager'),
        ),
        migrations.AddField(
            model_name='asmdailytarget',
            name='asm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='asm.asm'),
        ),
        migrations.AddField(
            model_name='asmdailytarget',
            name='zm_daily_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonemanager.zmdailytarget'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(related_name='roles', to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='asmdailytarget',
            unique_together={('asm', 'date')},
        ),
    ]
