# Generated by Django 5.2.6 on 2025-09-29 12:10

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0002_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asm',
            name='districts',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='states', chained_model_field='state', to='master.district'),
        ),
        migrations.AlterField(
            model_name='asm',
            name='offices',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='districts', chained_model_field='district', to='master.office'),
        ),
    ]
