# Generated by Django 4.2.19 on 2025-09-17 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonemanager', '0017_rename_achievement_value_zmdailytarget_activations_achieve_and_more'),
        ('asm', '0002_alter_asm_zone_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASMDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('application_target', models.FloatField(blank=True, default=0, null=True)),
                ('pop_target', models.FloatField(blank=True, default=0, null=True)),
                ('esign_target', models.FloatField(blank=True, default=0, null=True)),
                ('new_taluk_target', models.FloatField(blank=True, default=0, null=True)),
                ('new_live_partners_target', models.FloatField(blank=True, default=0, null=True)),
                ('activations_target', models.FloatField(blank=True, default=0, null=True)),
                ('calls_target', models.FloatField(blank=True, default=0, null=True)),
                ('sd_collection_target', models.FloatField(blank=True, default=0, null=True)),
                ('application_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('pop_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('esign_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('new_taluk_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('new_live_partners_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('activations_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('calls_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('sd_collection_achieve', models.FloatField(blank=True, default=0, null=True)),
                ('asm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='asm.asm')),
                ('zm_daily_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonemanager.zmdailytarget')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('asm', 'date')},
            },
        ),
    ]
