# Generated by Django 5.2.6 on 2025-09-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0002_alter_asm_options_remove_asm_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asm',
            name='otp',
            field=models.CharField(default='S001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='asm',
            name='otp_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asm',
            name='otp_generated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asm',
            name='otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
