# Generated by Django 5.2.6 on 2025-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0003_asmtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='asmtask',
            name='title',
            field=models.CharField(default='New Task', max_length=200),
        ),
    ]
