# Generated by Django 5.2.6 on 2025-09-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0003_asm_otp_asm_otp_allowed_asm_otp_generated_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asm',
            options={},
        ),
    ]
