# Generated by Django 5.2.6 on 2025-10-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0004_asmtask_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASMTask',
        ),
    ]
