# Generated by Django 5.2.6 on 2025-09-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0004_alter_asm_options'),
        ('master', '0003_alter_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asm',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asm',
            name='otp',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asmdistrictmapping',
            name='asm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='asm.asm'),
        ),
        migrations.AlterField(
            model_name='asmdistrictmapping',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asmdistrictmapping',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='master.district'),
        ),
        migrations.AlterField(
            model_name='asmstatemapping',
            name='asm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='asm.asm'),
        ),
        migrations.AlterField(
            model_name='asmstatemapping',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asmstatemapping',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='master.state'),
        ),
        migrations.AlterField(
            model_name='asmtalukmapping',
            name='asm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='asm.asm'),
        ),
        migrations.AlterField(
            model_name='asmtalukmapping',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asmtalukmapping',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='master.taluk'),
        ),
        migrations.AlterField(
            model_name='asmzonemapping',
            name='asm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='asm.asm'),
        ),
        migrations.AlterField(
            model_name='asmzonemapping',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asmzonemapping',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='master.zone'),
        ),
    ]
