# Generated by Django 5.2.6 on 2025-09-18 10:31

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asm', '0002_initial'),
        ('master', '0001_initial'),
        ('zonemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='asm.asm')),
                ('districts', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='states', chained_model_field='state', related_name='partners', to='master.district')),
                ('offices', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='districts', chained_model_field='district', related_name='partners', to='master.office')),
                ('states', models.ManyToManyField(blank=True, related_name='partners', to='master.state')),
                ('zone_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='zonemanager.zonemanager')),
            ],
        ),
    ]
