# Generated by Django 5.2.6 on 2025-09-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('zonemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='zone_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='zonemanager.zonemanager'),
        ),
    ]
