# Generated by Django 5.2.6 on 2025-09-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0004_alter_asm_group_alter_asm_user_and_more'),
        ('partner', '0002_initial'),
        ('zonemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='asm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asm.asm'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zone_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonemanager.zonemanager'),
        ),
    ]
